spring:
  data:
    mongodb:
      uri: mongodb://root:123456@127.0.0.1:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: false
      repositories:
        type: reactive
  cache:
    redis:
      key-prefix: eou
      use-key-prefix: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
    wiki.zyue.eou: DEBUG