version: "3.8"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data